//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStoreApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderInfo = new HashSet<OrderInfo>();
        }
    
        public int OrderId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public int PointId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> Code { get; set; }
        public int OrderStatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderInfo> OrderInfo { get; set; }
        public virtual OrderStatuses OrderStatuses { get; set; }
        public virtual PickupPoints PickupPoints { get; set; }
        public virtual Users Users { get; set; }
        public string PointAdress
        {
            get
            {
                string city = PickupPoints.Cities.CityName;

                string index = !string.IsNullOrEmpty(PickupPoints.PointIndex) ? $"{PickupPoints.PointIndex}" : "";

                return $"{index}, г.{city}, ул.{PickupPoints.Street}, д.{PickupPoints.House}";
            }
        }
    }
}
